[package]
name = "tp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
petgraph = "0.6.0"
rustc-hash = "1.1.0"
structopt = "0.3.25"
tinyset = "0.4.6"
